### ISSUE TITLE
Ajouter un premier connecteur SPI via FTDI

### ISSUE THREAD

**Issue by XdoctorwhoZ** [Panduza/panduza-py-legacy#12]
Il faut ajouter le support SPI via FTDI sur panduza.
Première étape, il faut créer un connecteur:
panduza-py/platform/panduza_platform/connectors/spi_master_base.py (classe générique pour le spi master)
panduza-py/platform/panduza_platform/connectors/spi_master_ftdi.py (classe pour générer un spi master avec le ftdi)

**Comment by XdoctorwhoZ** [comment]
Pour le spi_master_base.py
Se baser sur l'API du produit aardvark pour le spi master

**Comment by XdoctorwhoZ** [comment]
aardvark i2C adapter python api

**Comment by BCadet** [comment]
Est-ce que le driver spi_base ne devrait pas implémenter une seule fonction `transfer` plutôt que des fonctions `read` et `write` ?
une communication SPI est toujours bi-directionnelle: pour chaque bit envoyé sur la ligne MOSI, un bit est reçu sur la ligne MISO. Beaucoup de composants tirent avantages de cela pour remonter des informations (par exemple de status) et ainsi économiser une transaction avec l'host. Je pense vraiment que la `seule` fonction vraiment importante pour le SPI est le `transfer`, les HAL implémentent aussi des fonctions `read` et `write` mais qui ne sont souvent que des wrap de la fonction `transfer` avec un des 2 buffers qui est soit ignoré (le rx dans un `write`) ou préinitialisé à 0 (le tx dans un `read`).

@XdoctorwhoZ J'en profite pour soulever un point: l'ajout du SPI me fait me poser des questions sur la gestion de l'update mqtt dans le meta-driver. Un utilisateur faisant un `read` s'attend à recevoir une update dans l'atts correspondant avec les données lues. Or dans l'implémentation actuelle de la fonction `update_attribute` du meta-driver un message mqtt n'est publié uniquement si la valeur du champ à changé depuis le dernier update. Pour la communication SPI cela se traduit par une absence d'apparition du buffer de lecture si le contenu est identique à une lecture précédente. ça ne me semble pas être un comportement souhaitable, surtout qu'il existe un argument `push` qui contrôle l'envoi sur le mqtt. Je propose de modifier la fonction `update_attribute` pour sortir la condition de push de la condition "l'attribut à changé". ce qui permet ainsi de pouvoir forcer un push même si la valeur est la même tout en conservant la possibilité d'inhiber le push en cas de besoin.
