### ISSUE TITLE
[0.2.0] Missing device count in platform info

### ISSUE THREAD

**Issue by wardru** [Panduza/panduza-py-legacy#75]
J'ai testé la branche 0.2.0, et il me manque le nombre de devices dans l'info de la plateforme.

J'avais imaginé un mesage comme ça dans ma branche ag/next:

```json
{"info": {"type": "platform", "version": "0.0", "state": "run", "number_of_devices": 2}}
```

**Comment by XdoctorwhoZ** [comment]
Ok on peut faire comme ça. Je tente de te faire ça vite.

**Comment by XdoctorwhoZ** [comment]
bug fixed + doc updated
